version: '2'
services:
  db:
    image: mysql
    env_file: .env

  redis:
    image: redis
    ports:
      - "6379"

  elastic:
    image: elasticsearch
    ports:
      - "9200"

  web:
    build: .
    volumes:
      - .:/people
    env_file: .env
    environment:
      RAILS_ENV: $RAILS_ENV
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - elastic
    volumes:
      - .:/myapp